# Generated by Django 4.0.2 on 2022-03-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_s',
            new_name='user',
        ),
    ]
