# Generated by Django 4.0.2 on 2022-02-13 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=500, verbose_name='UID')),
                ('user_fname', models.CharField(max_length=200, verbose_name='First name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last name')),
                ('user_username', models.CharField(max_length=200, unique=True, verbose_name='Username')),
                ('user_password', models.CharField(max_length=200, verbose_name='Password')),
                ('pub_date', models.DateField(default=datetime.datetime(2022, 2, 13, 11, 38, 34, 638069, tzinfo=utc))),
            ],
        ),
    ]
