# Generated by Django 4.0.2 on 2022-02-13 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_position',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 12, 0, 38, 464583, tzinfo=utc)),
        ),
    ]
