# Generated by Django 4.0.2 on 2022-02-14 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_pub_date_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_image', models.ImageField(upload_to='')),
                ('pro_id', models.CharField(max_length=15, unique=True, verbose_name='Product id')),
                ('pro_name', models.CharField(max_length=150, verbose_name='Product name')),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pro_size', models.CharField(max_length=50, verbose_name='Size')),
                ('Catergoty', models.CharField(max_length=5, verbose_name='Catergory')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 7, 46, 21, 404678, tzinfo=utc)),
        ),
    ]
