# Generated by Django 4.0.2 on 2022-02-14 08:05

import backend.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_product_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=backend.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 8, 5, 36, 174985, tzinfo=utc)),
        ),
    ]
