# Generated by Django 4.0.2 on 2022-02-14 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_product_pro_image_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 8, 7, 58, 918829, tzinfo=utc)),
        ),
    ]
