# Generated by Django 4.0.2 on 2022-02-18 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_meat_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 18, 9, 25, 29, 463782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.IntegerField(max_length=500, verbose_name='UID'),
        ),
    ]
