# Generated by Django 4.0.2 on 2022-02-13 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_user_image_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 13, 0, 37, 462623, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('body', models.TextField(default='null')),
                ('created_on', models.DateTimeField(verbose_name='date commented')),
                ('active', models.BooleanField(default=False)),
                ('user_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.user')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
