# Generated by Django 4.0.2 on 2022-02-14 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_productmeat_alter_user_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productmeat',
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 12, 41, 28, 607743, tzinfo=utc)),
        ),
    ]
