# Generated by Django 4.0.2 on 2022-02-14 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_meatproduct_alter_user_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meatproduct',
            old_name='Catergoty',
            new_name='Catergoty2',
        ),
        migrations.RenameField(
            model_name='meatproduct',
            old_name='pro_id',
            new_name='pro2_id',
        ),
        migrations.RenameField(
            model_name='meatproduct',
            old_name='pro_image',
            new_name='pro2_image',
        ),
        migrations.RenameField(
            model_name='meatproduct',
            old_name='pro_name',
            new_name='pro2_name',
        ),
        migrations.RenameField(
            model_name='meatproduct',
            old_name='pro_price',
            new_name='pro2_price',
        ),
        migrations.RenameField(
            model_name='meatproduct',
            old_name='pro_size',
            new_name='pro2_size',
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 14, 13, 35, 4, 71894, tzinfo=utc)),
        ),
    ]
