# Generated by Django 4.0.2 on 2022-03-01 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_user_pub_date_alter_user_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 19, 55, 54, 677904, tzinfo=utc)),
        ),
    ]
