# Generated by Django 4.0.2 on 2022-03-02 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_id',
            field=models.CharField(max_length=50, verbose_name='Product id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 7, 20, 35, 432738, tzinfo=utc)),
        ),
    ]
