# Generated by Django 4.0.2 on 2022-03-04 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='contact',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='state',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
